version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1.18"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb
